#!/usr/bin/env bash
#
# Generate THIRD-PARTY-NOTICES.md: the licence text of every module linked into
# the shipped binary.
#
# This is an obligation, not a courtesy. Apache-2.0 §4, the BSD licences and MIT
# all require reproducing copyright notices in binary redistributions, and a Go
# provider is a statically linked binary containing all of them. Shipping only
# our own LICENSE satisfies our licence and none of theirs.
#
# Deliberately a script over `go list` and the module cache rather than a tool
# dependency: the output is then reproducible from the module graph alone, with
# nothing to keep pinned, and `go mod tidy` cannot change it behind our backs.
#
# Only real, linked dependencies are included. `go list -deps .` walks the main
# package's imports, so test-only and tool-only modules — tfplugindocs and its
# tree, terraform-plugin-testing — are excluded: they are not in the binary a
# user installs, so their notices do not belong in its archive.

set -euo pipefail

OUT="${1:-THIRD-PARTY-NOTICES.md}"
MODCACHE="$(go env GOMODCACHE)"

# Modules contributing code to the built binary, excluding the standard library
# and this module itself.
#
# Collected with a while-read loop rather than `mapfile`, which needs bash 4:
# macOS still ships bash 3.2 as /bin/bash, and this project is developed on
# macOS, so a bash-4 builtin would make the script fail for its main audience.
MODULES=""
MODULE_COUNT=0
while IFS= read -r mod; do
	[ -n "$mod" ] || continue
	MODULES="${MODULES}${mod}
"
	MODULE_COUNT=$((MODULE_COUNT + 1))
done <<EOF
$(go list -deps -f '{{if not .Standard}}{{if .Module}}{{.Module.Path}}@{{.Module.Version}}{{end}}{{end}}' . |
	grep -v '^github.com/guidoiaquinti/terraform-provider-lima' |
	grep -v '^@$' |
	sort -u)
EOF

if [ "$MODULE_COUNT" -eq 0 ]; then
	echo "gen-notices: no dependencies found; refusing to write an empty file" >&2
	exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
	echo "# Third-party notices"
	echo
	echo "\`terraform-provider-lima\` is distributed as a statically linked binary."
	echo "It contains code from the modules below, each under its own licence, whose"
	echo "notices are reproduced here as those licences require."
	echo
	echo "This file is generated by \`make notices\` — do not edit it. Regenerate it"
	echo "when dependencies change; \`make notices-check\` fails the build if it is stale."
	echo
	echo "## Modules"
	echo
	printf '%s' "$MODULES" | while IFS= read -r m; do
		[ -n "$m" ] || continue
		echo "- \`${m}\`"
	done
	echo

	missing=0
	while IFS= read -r m; do
		[ -n "$m" ] || continue
		dir="${MODCACHE}/${m}"
		# Escaping: the module cache lower-cases capitals as !x, and go list
		# reports the un-escaped path, so fall back to a glob when needed.
		if [ ! -d "$dir" ]; then
			dir="$(find "${MODCACHE}" -maxdepth 4 -type d -name "$(basename "$m")" 2>/dev/null | head -1)"
		fi

		# A glob rather than `ls | grep`: parsing ls breaks on unusual file
		# names, and shellcheck rightly refuses it (SC2010). Modules in practice
		# use one of these spellings, so an explicit list is both safer and
		# clearer about what counts as a licence file.
		lic=""
		for candidate in LICENSE LICENSE.md LICENSE.txt LICENCE LICENCE.md \
			LICENSE-MIT COPYING COPYING.md License license.md; do
			if [ -f "${dir}/${candidate}" ]; then
				lic="$candidate"
				break
			fi
		done
		echo "---"
		echo
		echo "## ${m}"
		echo
		if [ -n "$lic" ] && [ -f "${dir}/${lic}" ]; then
			echo '```'
			cat "${dir}/${lic}"
			echo '```'
		else
			echo "_No licence file found in the module cache for this module._"
			echo "_Check its repository before shipping a release._"
			missing=$((missing + 1))
		fi
		echo
	done <<MODLIST
$MODULES
MODLIST

	if [ "$missing" -gt 0 ]; then
		echo "gen-notices: ${missing} module(s) had no licence file" >&2
	fi
} >"$tmp"

mv "$tmp" "$OUT"
trap - EXIT

echo "wrote $OUT covering $MODULE_COUNT modules"
